source('https://rubygems.org')
gem('shoulda')
gem('sinatra')
gem('sinatra-contrib')
gem('rspec')
gem('capybara')
gem('pry')
gem('launchy')
gem('pg')
gem('sinatra-activerecord')
gem('rake')
gem("shoulda-matchers", '~> 2.0')
